# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'testProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for testProject
  pod 'ALCameraViewController'
  pod 'CameraKit-iOS'
  pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
  pod 'Alamofire'
end
